<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_AxisWithRefSwitch" Id="{873109b6-fdee-4331-b6d5-72f8c80c8d32}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_AxisWithRefSwitch
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	prox AT %I* : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="HomingSensor" Id="{6ab18b84-3041-4610-a46a-ae3856c5c165}">
      <Declaration><![CDATA[PROPERTY HomingSensor : BOOL]]></Declaration>
      <Get Name="Get" Id="{a15d6c32-be12-4f43-9206-cbb7edca1e86}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[HomingSensor := prox;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="FB_AxisWithRefSwitch">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_AxisWithRefSwitch.HomingSensor.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>