<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="POU" Id="{392f3106-ebc3-4727-8994-a3d53f78cda8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK POU
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>